
admin:
  address:
    socket_address: 
      address: 0.0.0.0 
      port_value: 8081

static_resources:
  listeners:
    - name: default_listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 80
      filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              codec_type: auto
              stat_prefix: ingress_http
# custom_reply_start
              local_reply_config:
                mappers:
                - filter:
                    status_code_filter:
                      comparison:
                        op: EQ
                        value:
                          default_value: 503
                          runtime_key: key_b
                  status_code: 509
                  body_format_override:
                    text_format: "<h1>%LOCAL_REPLY_BODY% %REQ(:path)% moep</h1>"
                    content_type: "text/html; charset=UTF-8"
# custom_reply_end                
              route_config:
                name: local_route
                virtual_hosts:
                  - name: backend
                    domains: ["*"]
                    routes:
                      - match: { prefix: "/0" }
                        route:
                          cluster: service_backend00
                          prefix_rewrite: "/"
# fresh start
                        typed_per_filter_config:
                          envoy.filters.http.local_ratelimit:
                            "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
                            stat_prefix: route0_rate_limit
                            token_bucket: # 10 req/min 
                              max_tokens: 10
                              tokens_per_fill: 10
                              fill_interval: 60s
                            filter_enabled:
                              runtime_key: route2_limit_enabled
                              default_value:
                                numerator: 100
                                denominator: HUNDRED
                            filter_enforced:
                              runtime_key: route0_limit_enforced
                              default_value:
                                numerator: 100
                                denominator: HUNDRED
# fresh end
                      - match: { prefix: "/1" }
                        route: 
                          cluster: service_backend01
                          prefix_rewrite: "/"
                      - match: { prefix: "/" }
                        route: 
                          cluster: service_backend00
                          prefix_rewrite: "/"
# fresh start
                        typed_per_filter_config:
                          envoy.filters.http.local_ratelimit:
                            "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
                            stat_prefix: route_root_rate_limit
                            token_bucket: #1000 req/min
                              max_tokens: 1000
                              tokens_per_fill: 1000
                              fill_interval: 60s
                            filter_enabled:
                              runtime_key: route2_limit_enabled
                              default_value:
                                numerator: 100
                                denominator: HUNDRED
                            filter_enforced:
                              runtime_key: route0_limit_enforced
                              default_value:
                                numerator: 100
                                denominator: HUNDRED
# fresh end
              http_filters:
# fresh start
                - name: envoy.filters.http.local_ratelimit
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
                    stat_prefix: route0_rate_limit

                - name: envoy.filters.http.local_ratelimit
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
                    stat_prefix: route_root_rate_limit
# fresh end
                - name: envoy.filters.http.router
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
    - name: service_backend00
      connect_timeout: 0.25s
      type: STATIC
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: service_backend00
        endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 10.7.0.20
                    port_value: 8888


    - name: service_backend01
      connect_timeout: 0.25s
      type: STATIC
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: service_backend01
        endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 10.7.0.20
                    port_value: 8889
